<?php

namespace DoctrineProxies\__CG__\Entity\app\a5;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Employee extends \Entity\app\a5\Employee implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getJob()
    {
        $this->__load();
        return parent::getJob();
    }

    public function setJob($job)
    {
        $this->__load();
        return parent::setJob($job);
    }

    public function getIdNumber()
    {
        $this->__load();
        return parent::getIdNumber();
    }

    public function setIdNumber($idNumber)
    {
        $this->__load();
        return parent::setIdNumber($idNumber);
    }

    public function getTenant()
    {
        $this->__load();
        return parent::getTenant();
    }

    public function setTenant($tenant)
    {
        $this->__load();
        return parent::setTenant($tenant);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getSecondName()
    {
        $this->__load();
        return parent::getSecondName();
    }

    public function setSecondName($secondName)
    {
        $this->__load();
        return parent::setSecondName($secondName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getReligion()
    {
        $this->__load();
        return parent::getReligion();
    }

    public function setReligion($religion)
    {
        $this->__load();
        return parent::setReligion($religion);
    }

    public function getBirthDate()
    {
        $this->__load();
        return parent::getBirthDate();
    }

    public function setBirthDate($birthDate)
    {
        $this->__load();
        return parent::setBirthDate($birthDate);
    }

    public function getBirthPlace()
    {
        $this->__load();
        return parent::getBirthPlace();
    }

    public function setBirthPlace($birthPlace)
    {
        $this->__load();
        return parent::setBirthPlace($birthPlace);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function setAddress($address)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function getEmailAddress()
    {
        $this->__load();
        return parent::getEmailAddress();
    }

    public function setEmailAddress($emailAddress)
    {
        $this->__load();
        return parent::setEmailAddress($emailAddress);
    }

    public function getPhoneNumber1()
    {
        $this->__load();
        return parent::getPhoneNumber1();
    }

    public function setPhoneNumber1($phoneNumber1)
    {
        $this->__load();
        return parent::setPhoneNumber1($phoneNumber1);
    }

    public function getPhoneNumber2()
    {
        $this->__load();
        return parent::getPhoneNumber2();
    }

    public function setPhoneNumber2($phoneNumber2)
    {
        $this->__load();
        return parent::setPhoneNumber2($phoneNumber2);
    }

    public function getFaxNumber1()
    {
        $this->__load();
        return parent::getFaxNumber1();
    }

    public function setFaxNumber1($faxNumber1)
    {
        $this->__load();
        return parent::setFaxNumber1($faxNumber1);
    }

    public function getFaxNumber2()
    {
        $this->__load();
        return parent::getFaxNumber2();
    }

    public function setFaxNumber2($faxNumber2)
    {
        $this->__load();
        return parent::setFaxNumber2($faxNumber2);
    }

    public function getActiveFlag()
    {
        $this->__load();
        return parent::getActiveFlag();
    }

    public function setActiveFlag($activeFlag)
    {
        $this->__load();
        return parent::setActiveFlag($activeFlag);
    }

    public function getCreateOn()
    {
        $this->__load();
        return parent::getCreateOn();
    }

    public function setCreateOn($createOn)
    {
        $this->__load();
        return parent::setCreateOn($createOn);
    }

    public function getFoto()
    {
        $this->__load();
        return parent::getFoto();
    }

    public function setFoto($foto)
    {
        $this->__load();
        return parent::setFoto($foto);
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'idNumber', 'firstName', 'secondName', 'lastName', 'birthDate', 'birthPlace', 'address', 'emailAddress', 'phoneNumber1', 'phoneNumber2', 'faxNumber1', 'faxNumber2', 'activeFlag', 'createOn', 'foto', 'tenant', 'job', 'gender', 'religion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}