<?php

namespace DoctrineProxies\__CG__\Entity\app\a2;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Menu extends \Entity\app\a2\Menu implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function addMenus($menus)
    {
        $this->__load();
        return parent::addMenus($menus);
    }

    public function removeMenus($menus)
    {
        $this->__load();
        return parent::removeMenus($menus);
    }

    public function getMenuList()
    {
        $this->__load();
        return parent::getMenuList();
    }

    public function getMenus()
    {
        $this->__load();
        return parent::getMenus();
    }

    public function setMenus($menus)
    {
        $this->__load();
        return parent::setMenus($menus);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getMenuCode()
    {
        $this->__load();
        return parent::getMenuCode();
    }

    public function setMenuCode($menuCode)
    {
        $this->__load();
        return parent::setMenuCode($menuCode);
    }

    public function getMenuName()
    {
        $this->__load();
        return parent::getMenuName();
    }

    public function setMenuName($menuName)
    {
        $this->__load();
        return parent::setMenuName($menuName);
    }

    public function getMenuType()
    {
        $this->__load();
        return parent::getMenuType();
    }

    public function setMenuType($menuType)
    {
        $this->__load();
        return parent::setMenuType($menuType);
    }

    public function getMenuCommand()
    {
        $this->__load();
        return parent::getMenuCommand();
    }

    public function setMenuCommand($menuCommand)
    {
        $this->__load();
        return parent::setMenuCommand($menuCommand);
    }

    public function getSystemFlag()
    {
        $this->__load();
        return parent::getSystemFlag();
    }

    public function setSystemFlag($systemFlag)
    {
        $this->__load();
        return parent::setSystemFlag($systemFlag);
    }

    public function getAdminFlag()
    {
        $this->__load();
        return parent::getAdminFlag();
    }

    public function setAdminFlag($adminFlag)
    {
        $this->__load();
        return parent::setAdminFlag($adminFlag);
    }

    public function getCreateOn()
    {
        $this->__load();
        return parent::getCreateOn();
    }

    public function setCreateOn($createOn)
    {
        $this->__load();
        return parent::setCreateOn($createOn);
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function setParent($parent)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function getActiveFlag()
    {
        $this->__load();
        return parent::getActiveFlag();
    }

    public function setActiveFlag($activeFlag)
    {
        $this->__load();
        return parent::setActiveFlag($activeFlag);
    }

    public function getWindow()
    {
        $this->__load();
        return parent::getWindow();
    }

    public function setWindow($window)
    {
        $this->__load();
        return parent::setWindow($window);
    }

    public function getCreateBy()
    {
        $this->__load();
        return parent::getCreateBy();
    }

    public function setCreateBy($createBy)
    {
        $this->__load();
        return parent::setCreateBy($createBy);
    }

    public function getUpdateOn()
    {
        $this->__load();
        return parent::getUpdateOn();
    }

    public function setUpdateOn($updateOn)
    {
        $this->__load();
        return parent::setUpdateOn($updateOn);
    }

    public function getUpdateBy()
    {
        $this->__load();
        return parent::getUpdateBy();
    }

    public function setUpdateBy($updateBy)
    {
        $this->__load();
        return parent::setUpdateBy($updateBy);
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'menuCode', 'menuName', 'menuCommand', 'systemFlag', 'createOn', 'activeFlag', 'adminFlag', 'window', 'updateOn', 'menuType', 'parent', 'createBy', 'updateBy', 'menus');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}