<?php

namespace DoctrineProxies\__CG__\Entity\content;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Patient extends \Entity\content\Patient implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function addVisits($visits)
    {
        $this->__load();
        return parent::addVisits($visits);
    }

    public function removeVisits($visits)
    {
        $this->__load();
        return parent::removeVisits($visits);
    }

    public function getVistsList()
    {
        $this->__load();
        return parent::getVistsList();
    }

    public function getVisits()
    {
        $this->__load();
        return parent::getVisits();
    }

    public function setVists($visits)
    {
        $this->__load();
        return parent::setVists($visits);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getKtp()
    {
        $this->__load();
        return parent::getKtp();
    }

    public function setKtp($ktp)
    {
        $this->__load();
        return parent::setKtp($ktp);
    }

    public function getPostalCode()
    {
        $this->__load();
        return parent::getPostalCode();
    }

    public function setPostalCode($postalCode)
    {
        $this->__load();
        return parent::setPostalCode($postalCode);
    }

    public function getPatientCode()
    {
        $this->__load();
        return parent::getPatientCode();
    }

    public function setPatientCode($patientCode)
    {
        $this->__load();
        return parent::setPatientCode($patientCode);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getBirthPlace()
    {
        $this->__load();
        return parent::getBirthPlace();
    }

    public function setBirthPlace($birthPlace)
    {
        $this->__load();
        return parent::setBirthPlace($birthPlace);
    }

    public function getBirthDate()
    {
        $this->__load();
        return parent::getBirthDate();
    }

    public function setBirthDate($birthDate)
    {
        $this->__load();
        return parent::setBirthDate($birthDate);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getReligion()
    {
        $this->__load();
        return parent::getReligion();
    }

    public function setReligion($religion)
    {
        $this->__load();
        return parent::setReligion($religion);
    }

    public function getBlod()
    {
        $this->__load();
        return parent::getBlod();
    }

    public function setBlod($blod)
    {
        $this->__load();
        return parent::setBlod($blod);
    }

    public function getEdu()
    {
        $this->__load();
        return parent::getEdu();
    }

    public function setEdu($edu)
    {
        $this->__load();
        return parent::setEdu($edu);
    }

    public function getPhoneNumber()
    {
        $this->__load();
        return parent::getPhoneNumber();
    }

    public function setPhoneNumber($phoneNumber)
    {
        $this->__load();
        return parent::setPhoneNumber($phoneNumber);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function setAddress($address)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function getRt()
    {
        $this->__load();
        return parent::getRt();
    }

    public function setRt($rt)
    {
        $this->__load();
        return parent::setRt($rt);
    }

    public function getRw()
    {
        $this->__load();
        return parent::getRw();
    }

    public function setRw($rw)
    {
        $this->__load();
        return parent::setRw($rw);
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function setCountry($country)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function getProvince()
    {
        $this->__load();
        return parent::getProvince();
    }

    public function setProvince($province)
    {
        $this->__load();
        return parent::setProvince($province);
    }

    public function getDistrict()
    {
        $this->__load();
        return parent::getDistrict();
    }

    public function setDistrict($district)
    {
        $this->__load();
        return parent::setDistrict($district);
    }

    public function getDistricts()
    {
        $this->__load();
        return parent::getDistricts();
    }

    public function setDistricts($districts)
    {
        $this->__load();
        return parent::setDistricts($districts);
    }

    public function getKelurahan()
    {
        $this->__load();
        return parent::getKelurahan();
    }

    public function setKelurahan($kelurahan)
    {
        $this->__load();
        return parent::setKelurahan($kelurahan);
    }

    public function getCountryTemp()
    {
        $this->__load();
        return parent::getCountryTemp();
    }

    public function setCountryTemp($countryTemp)
    {
        $this->__load();
        return parent::setCountryTemp($countryTemp);
    }

    public function getProvinceTemp()
    {
        $this->__load();
        return parent::getProvinceTemp();
    }

    public function setProvinceTemp($provinceTemp)
    {
        $this->__load();
        return parent::setProvinceTemp($provinceTemp);
    }

    public function getDistrictTemp()
    {
        $this->__load();
        return parent::getDistrictTemp();
    }

    public function setDistrictTemp($districtTemp)
    {
        $this->__load();
        return parent::setDistrictTemp($districtTemp);
    }

    public function getDistrictsTemp()
    {
        $this->__load();
        return parent::getDistrictsTemp();
    }

    public function setDistrictsTemp($districtsTemp)
    {
        $this->__load();
        return parent::setDistrictsTemp($districtsTemp);
    }

    public function getKelurahanTemp()
    {
        $this->__load();
        return parent::getKelurahanTemp();
    }

    public function setKelurahanTemp($kelurahanTemp)
    {
        $this->__load();
        return parent::setKelurahanTemp($kelurahanTemp);
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'patientCode', 'ktp', 'title', 'name', 'birthPlace', 'birthDate', 'address', 'rt', 'rw', 'postalCode', 'phoneNumber', 'gender', 'religion', 'blod', 'edu', 'country', 'countryTemp', 'province', 'provinceTemp', 'district', 'districtTemp', 'districts', 'districtsTemp', 'kelurahan', 'kelurahanTemp', 'visits');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}