<?php

namespace DoctrineProxies\__CG__\Entity\app\a4;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Parameter extends \Entity\app\a4\Parameter implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function addParameterOptions($parameterOptions)
    {
        $this->__load();
        return parent::addParameterOptions($parameterOptions);
    }

    public function removeParameterOptions($parameterOptions)
    {
        $this->__load();
        return parent::removeParameterOptions($parameterOptions);
    }

    public function getParameterOptionList()
    {
        $this->__load();
        return parent::getParameterOptionList();
    }

    public function getParameterOptions()
    {
        $this->__load();
        return parent::getParameterOptions();
    }

    public function setParameterOptions($parameterOptions)
    {
        $this->__load();
        return parent::setParameterOptions($parameterOptions);
    }

    public function getParameterCode()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["parameterCode"];
        }
        $this->__load();
        return parent::getParameterCode();
    }

    public function setParameterCode($parameterCode)
    {
        $this->__load();
        return parent::setParameterCode($parameterCode);
    }

    public function getParameterName()
    {
        $this->__load();
        return parent::getParameterName();
    }

    public function setParameterName($parameterName)
    {
        $this->__load();
        return parent::setParameterName($parameterName);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getActiveFlag()
    {
        $this->__load();
        return parent::getActiveFlag();
    }

    public function setActiveFlag($activeFlag)
    {
        $this->__load();
        return parent::setActiveFlag($activeFlag);
    }

    public function getSystemFlag()
    {
        $this->__load();
        return parent::getSystemFlag();
    }

    public function setSystemFlag($systemFlag)
    {
        $this->__load();
        return parent::setSystemFlag($systemFlag);
    }

    public function getCreateOn()
    {
        $this->__load();
        return parent::getCreateOn();
    }

    public function setCreateOn($createOn)
    {
        $this->__load();
        return parent::setCreateOn($createOn);
    }

    public function getResume()
    {
        $this->__load();
        return parent::getResume();
    }

    public function setResume($resume)
    {
        $this->__load();
        return parent::setResume($resume);
    }

    public function getCreateBy()
    {
        $this->__load();
        return parent::getCreateBy();
    }

    public function setCreateBy($createBy)
    {
        $this->__load();
        return parent::setCreateBy($createBy);
    }

    public function getUpdateOn()
    {
        $this->__load();
        return parent::getUpdateOn();
    }

    public function setUpdateOn($updateOn)
    {
        $this->__load();
        return parent::setUpdateOn($updateOn);
    }

    public function getUpdateBy()
    {
        $this->__load();
        return parent::getUpdateBy();
    }

    public function setUpdateBy($updateBy)
    {
        $this->__load();
        return parent::setUpdateBy($updateBy);
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'parameterCode', 'parameterName', 'description', 'resume', 'activeFlag', 'systemFlag', 'createOn', 'updateOn', 'createBy', 'updateBy', 'parameterOptions');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}