<?php

namespace DoctrineProxies\__CG__\Entity\content;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Rujukan extends \Entity\content\Rujukan implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getNomorRujukan()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["nomorRujukan"];
        }
        $this->__load();
        return parent::getNomorRujukan();
    }

    public function setNomorRujukan($nomorRujukan)
    {
        $this->__load();
        return parent::setNomorRujukan($nomorRujukan);
    }

    public function getPasien()
    {
        $this->__load();
        return parent::getPasien();
    }

    public function setPasien($pasien)
    {
        $this->__load();
        return parent::setPasien($pasien);
    }

    public function getDeleteFlag()
    {
        $this->__load();
        return parent::getDeleteFlag();
    }

    public function setDeleteFlag($deleteFlag)
    {
        $this->__load();
        return parent::setDeleteFlag($deleteFlag);
    }

    public function getDeleteBalikFlag()
    {
        $this->__load();
        return parent::getDeleteBalikFlag();
    }

    public function setDeleteBalikFlag($deleteBalikFlag)
    {
        $this->__load();
        return parent::setDeleteBalikFlag($deleteBalikFlag);
    }

    public function getAlasanBlok()
    {
        $this->__load();
        return parent::getAlasanBlok();
    }

    public function setAlasanBlok($alasanBlok)
    {
        $this->__load();
        return parent::setAlasanBlok($alasanBlok);
    }

    public function getRujukBalik()
    {
        $this->__load();
        return parent::getRujukBalik();
    }

    public function setRujukBalik($rujukBalik)
    {
        $this->__load();
        return parent::setRujukBalik($rujukBalik);
    }

    public function getFaskes()
    {
        $this->__load();
        return parent::getFaskes();
    }

    public function setFaskes($faskes)
    {
        $this->__load();
        return parent::setFaskes($faskes);
    }

    public function getStatusVerifikasi()
    {
        $this->__load();
        return parent::getStatusVerifikasi();
    }

    public function setStatusVerifikasi($statusVerifikasi)
    {
        $this->__load();
        return parent::setStatusVerifikasi($statusVerifikasi);
    }

    public function getTglRujukRb()
    {
        $this->__load();
        return parent::getTglRujukRb();
    }

    public function setTglRujukRb($tglRujukRb)
    {
        $this->__load();
        return parent::setTglRujukRb($tglRujukRb);
    }

    public function getKonsultasiRb()
    {
        $this->__load();
        return parent::getKonsultasiRb();
    }

    public function setKonsultasiRb($konsultasiRb)
    {
        $this->__load();
        return parent::setKonsultasiRb($konsultasiRb);
    }

    public function getRwiRb()
    {
        $this->__load();
        return parent::getRwiRb();
    }

    public function setRwiRb($rwiRb)
    {
        $this->__load();
        return parent::setRwiRb($rwiRb);
    }

    public function getDokterRb()
    {
        $this->__load();
        return parent::getDokterRb();
    }

    public function setDokterRb($dokterRb)
    {
        $this->__load();
        return parent::setDokterRb($dokterRb);
    }

    public function getOtherRb()
    {
        $this->__load();
        return parent::getOtherRb();
    }

    public function setOtherRb($otherRb)
    {
        $this->__load();
        return parent::setOtherRb($otherRb);
    }

    public function getControlDateRb()
    {
        $this->__load();
        return parent::getControlDateRb();
    }

    public function setControlDateRb($controlDateRb)
    {
        $this->__load();
        return parent::setControlDateRb($controlDateRb);
    }

    public function getObatRb()
    {
        $this->__load();
        return parent::getObatRb();
    }

    public function setObatRb($obatRb)
    {
        $this->__load();
        return parent::setObatRb($obatRb);
    }

    public function getTerapiRb()
    {
        $this->__load();
        return parent::getTerapiRb();
    }

    public function setTerapiRb($terapiRb)
    {
        $this->__load();
        return parent::setTerapiRb($terapiRb);
    }

    public function getDiagnosaRb()
    {
        $this->__load();
        return parent::getDiagnosaRb();
    }

    public function setDiagnosaRb($diagnosaRb)
    {
        $this->__load();
        return parent::setDiagnosaRb($diagnosaRb);
    }

    public function getTanggalRujuk()
    {
        $this->__load();
        return parent::getTanggalRujuk();
    }

    public function setTanggalRujuk($tanggalRujuk)
    {
        $this->__load();
        return parent::setTanggalRujuk($tanggalRujuk);
    }

    public function getFaskesDokter()
    {
        $this->__load();
        return parent::getFaskesDokter();
    }

    public function setFaskesDokter($faskesDokter)
    {
        $this->__load();
        return parent::setFaskesDokter($faskesDokter);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getPenyakit()
    {
        $this->__load();
        return parent::getPenyakit();
    }

    public function setPenyakit($penyakit)
    {
        $this->__load();
        return parent::setPenyakit($penyakit);
    }

    public function getTindakan()
    {
        $this->__load();
        return parent::getTindakan();
    }

    public function setTindakan($tindakan)
    {
        $this->__load();
        return parent::setTindakan($tindakan);
    }

    public function getObat()
    {
        $this->__load();
        return parent::getObat();
    }

    public function setObat($obat)
    {
        $this->__load();
        return parent::setObat($obat);
    }

    public function getUmur()
    {
        $this->__load();
        return parent::getUmur();
    }

    public function setUmur($umur)
    {
        $this->__load();
        return parent::setUmur($umur);
    }

    public function getPenjamin()
    {
        $this->__load();
        return parent::getPenjamin();
    }

    public function setPenjamin($penjamin)
    {
        $this->__load();
        return parent::setPenjamin($penjamin);
    }

    public function getNomorBpjs()
    {
        $this->__load();
        return parent::getNomorBpjs();
    }

    public function setNomorBpjs($nomorBpjs)
    {
        $this->__load();
        return parent::setNomorBpjs($nomorBpjs);
    }

    public function getCatatan()
    {
        $this->__load();
        return parent::getCatatan();
    }

    public function setCatatan($catatan)
    {
        $this->__load();
        return parent::setCatatan($catatan);
    }

    public function getPenunjang()
    {
        $this->__load();
        return parent::getPenunjang();
    }

    public function setPenunjang($penunjang)
    {
        $this->__load();
        return parent::setPenunjang($penunjang);
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'nomorRujukan', 'tanggalRujuk', 'faskesDokter', 'tindakan', 'obat', 'umur', 'penjamin', 'alasanBlok', 'nomorBpjs', 'catatan', 'penunjang', 'rujukBalik', 'deleteFlag', 'deleteBalikFlag', 'terapiRb', 'obatRb', 'controlDateRb', 'otherRb', 'rwiRb', 'konsultasiRb', 'tglRujukRb', 'pasien', 'faskes', 'status', 'penyakit', 'statusVerifikasi', 'diagnosaRb', 'dokterRb');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}