<?php

namespace DoctrineProxies\__CG__\Entity\content;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Visit extends \Entity\content\Visit implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getJsonSep()
    {
        $this->__load();
        return parent::getJsonSep();
    }

    public function setJsonSep($jsonSep)
    {
        $this->__load();
        return parent::setJsonSep($jsonSep);
    }

    public function getJsonBpjs()
    {
        $this->__load();
        return parent::getJsonBpjs();
    }

    public function setJsonBpjs($jsonBpjs)
    {
        $this->__load();
        return parent::setJsonBpjs($jsonBpjs);
    }

    public function getPenyakit()
    {
        $this->__load();
        return parent::getPenyakit();
    }

    public function setPenyakit($penyakit)
    {
        $this->__load();
        return parent::setPenyakit($penyakit);
    }

    public function getPbi()
    {
        $this->__load();
        return parent::getPbi();
    }

    public function setPbi($pbi)
    {
        $this->__load();
        return parent::setPbi($pbi);
    }

    public function getNonPbi()
    {
        $this->__load();
        return parent::getNonPbi();
    }

    public function setNonPbi($nonPbi)
    {
        $this->__load();
        return parent::setNonPbi($nonPbi);
    }

    public function getPatient()
    {
        $this->__load();
        return parent::getPatient();
    }

    public function setPatient($patient)
    {
        $this->__load();
        return parent::setPatient($patient);
    }

    public function getUnit()
    {
        $this->__load();
        return parent::getUnit();
    }

    public function setUnit($unit)
    {
        $this->__load();
        return parent::setUnit($unit);
    }

    public function getEntryDate()
    {
        $this->__load();
        return parent::getEntryDate();
    }

    public function setEntryDate($entryDate)
    {
        $this->__load();
        return parent::setEntryDate($entryDate);
    }

    public function getEntrySeq()
    {
        $this->__load();
        return parent::getEntrySeq();
    }

    public function setEntrySeq($entrySeq)
    {
        $this->__load();
        return parent::setEntrySeq($entrySeq);
    }

    public function getCatatanPerubahan()
    {
        $this->__load();
        return parent::getCatatanPerubahan();
    }

    public function setCatatanPerubahan($catatanPerubahan)
    {
        $this->__load();
        return parent::setCatatanPerubahan($catatanPerubahan);
    }

    public function getDokter()
    {
        $this->__load();
        return parent::getDokter();
    }

    public function setDokter($dokter)
    {
        $this->__load();
        return parent::setDokter($dokter);
    }

    public function getBaru()
    {
        $this->__load();
        return parent::getBaru();
    }

    public function setBaru($baru)
    {
        $this->__load();
        return parent::setBaru($baru);
    }

    public function getRujukan()
    {
        $this->__load();
        return parent::getRujukan();
    }

    public function setRujukan($rujukan)
    {
        $this->__load();
        return parent::setRujukan($rujukan);
    }

    public function getAntrian()
    {
        $this->__load();
        return parent::getAntrian();
    }

    public function setAntrian($antrian)
    {
        $this->__load();
        return parent::setAntrian($antrian);
    }

    public function getCustomer()
    {
        $this->__load();
        return parent::getCustomer();
    }

    public function setCustomer($customer)
    {
        $this->__load();
        return parent::setCustomer($customer);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getJenisDaftar()
    {
        $this->__load();
        return parent::getJenisDaftar();
    }

    public function setJenisDaftar($jenisDaftar)
    {
        $this->__load();
        return parent::setJenisDaftar($jenisDaftar);
    }

    public function getKodeSep()
    {
        $this->__load();
        return parent::getKodeSep();
    }

    public function setKodeSep($kodeSep)
    {
        $this->__load();
        return parent::setKodeSep($kodeSep);
    }

    public function getNamaPeserta()
    {
        $this->__load();
        return parent::getNamaPeserta();
    }

    public function setNamaPeserta($namaPeserta)
    {
        $this->__load();
        return parent::setNamaPeserta($namaPeserta);
    }

    public function getNomorPeserta()
    {
        $this->__load();
        return parent::getNomorPeserta();
    }

    public function setNomorPeserta($nomorPeserta)
    {
        $this->__load();
        return parent::setNomorPeserta($nomorPeserta);
    }

    public function getNomorPendaftaran()
    {
        $this->__load();
        return parent::getNomorPendaftaran();
    }

    public function setNomorPendaftaran($nomorPendaftaran)
    {
        $this->__load();
        return parent::setNomorPendaftaran($nomorPendaftaran);
    }

    public function getHadir()
    {
        $this->__load();
        return parent::getHadir();
    }

    public function setHadir($hadir)
    {
        $this->__load();
        return parent::setHadir($hadir);
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'entryDate', 'entrySeq', 'antrian', 'status', 'kodeSep', 'namaPeserta', 'catatanPerubahan', 'nomorPeserta', 'nomorPendaftaran', 'hadir', 'baru', 'pbi', 'nonPbi', 'jsonBpjs', 'jsonSep', 'patient', 'unit', 'dokter', 'customer', 'jenisDaftar', 'rujukan', 'penyakit');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}