<?php

namespace DoctrineProxies\__CG__\Entity\app\a3;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Role extends \Entity\app\a3\Role implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function addRoleMenus($roleMenus)
    {
        $this->__load();
        return parent::addRoleMenus($roleMenus);
    }

    public function removeRoleMenus($roleMenus)
    {
        $this->__load();
        return parent::removeRoleMenus($roleMenus);
    }

    public function getRoleMenuList()
    {
        $this->__load();
        return parent::getRoleMenuList();
    }

    public function getRoleMenus()
    {
        $this->__load();
        return parent::getRoleMenus();
    }

    public function setRoleMenus($roleMenus)
    {
        $this->__load();
        return parent::setRoleMenus($roleMenus);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getRoleCode()
    {
        $this->__load();
        return parent::getRoleCode();
    }

    public function setRoleCode($roleCode)
    {
        $this->__load();
        return parent::setRoleCode($roleCode);
    }

    public function getRoleName()
    {
        $this->__load();
        return parent::getRoleName();
    }

    public function setRoleName($roleName)
    {
        $this->__load();
        return parent::setRoleName($roleName);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getCreateOn()
    {
        $this->__load();
        return parent::getCreateOn();
    }

    public function setCreateOn($createOn)
    {
        $this->__load();
        return parent::setCreateOn($createOn);
    }

    public function getTenant()
    {
        $this->__load();
        return parent::getTenant();
    }

    public function setTenant($tenant)
    {
        $this->__load();
        return parent::setTenant($tenant);
    }

    public function getActiveFlag()
    {
        $this->__load();
        return parent::getActiveFlag();
    }

    public function setActiveFlag($activeFlag)
    {
        $this->__load();
        return parent::setActiveFlag($activeFlag);
    }

    public function getCreateby()
    {
        $this->__load();
        return parent::getCreateby();
    }

    public function setCreateby($createBy)
    {
        $this->__load();
        return parent::setCreateby($createBy);
    }

    public function getUpdateOn()
    {
        $this->__load();
        return parent::getUpdateOn();
    }

    public function setUpdateOn($updateOn)
    {
        $this->__load();
        return parent::setUpdateOn($updateOn);
    }

    public function getUpdateBy()
    {
        $this->__load();
        return parent::getUpdateBy();
    }

    public function setUpdateBy($updateBy)
    {
        $this->__load();
        return parent::setUpdateBy($updateBy);
    }

    public function update()
    {
        $this->__load();
        return parent::update();
    }

    public function getById($id)
    {
        $this->__load();
        return parent::getById($id);
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'roleCode', 'roleName', 'description', 'createOn', 'activeFlag', 'updateOn', 'tenant', 'createBy', 'updateBy', 'roleMenus');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}